export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGIN';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGIN_ERROR';
export const FETCH_MY_RUNS = 'FETCH_MY_RUNS';
export const FETCH_MY_RUNS_ERROR = 'FETCH_MY_RUNS_ERROR';
export const FETCH_FRIENDS_RUNS = 'FETCH_FRIENDS_RUNS';
export const FETCH_FRIENDS_RUNS_ERROR = 'FETCH_FRIENDS_RUNS_ERROR';